# Main settings
title: Моделирование месторождений
email: k.bryzgin@yandex.ru
description: >-
  Блог, посвященный блочному моделированию месторождений
baseurl: /mm-blog/
url: https://bryzgin.github.io/mm-blog/
show_excerpts: false

# Social links
github_username: bryzgin
rss: RSS

# Build settings
theme: minima
plugins:
  - jekyll-feed