title: Моделирование месторождений
email: k.bryzgin@yandex.ru
description: >-
  Блог посвященный блочному моделированию месторождений твердых полезных ископаемых
baseurl: /mm-blog/
url: https://bryzgin.github.io/mm-blog/

# Build settings
theme: minima
plugins:
  - jekyll-feed